config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-out', to: 'authentication#destroy'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  private
  def current_user
    if session[:user_id].present?
      User.find(session[:user_id])
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'You are now signed out!'
  end
  def new

  end
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'You are now signed in!'
    else
      flash[:notice] = 'Something went wrong'
      render :new
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'You are now signed up!'
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.haml
.container
  .page-header
    %h1 Sign In
  .form-horizontal
    =form_tag url: sign_in_path do |f|
      .form-group
        =label_tag :email
        =email_field_tag :email
      .form-group
        =label_tag :password
        =password_field_tag :password
      .form-group
        =submit_tag 'Sign In', class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title AutheticationPractice02
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %p
        -if notice
          .alert.alert-success
            =notice
    =yield    

app/views/welcome/index.html.haml
.container
  .page-header
    %h1 Welcome
  .well
    -if current_user
      ='Logged in as: ' + current_user.email
      =link_to 'Sign Out', sign_out_path, class: 'btn btn-danger'
    -else
      =link_to 'Sign Up', sign_up_path, class: 'btn btn-default'
      =link_to 'Sign In', sign_in_path, class: 'btn btn-primary'